apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: { name: pipelines.stable.conveyer.com }
spec:
  scope: Namespaced
  group: stable.conveyer.com
  names:
    singular: pipeline
    kind: Pipeline
    plural: pipelines
    shortNames: [pl]
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                jobs:
                  type: array
                  items:
                    type: object
                    properties:
                      name: { type: string }
